### ISSUE TITLE
Status? Dead, abandoned or?

### ISSUE THREAD

**Issue by Bartolomeus-649** [DevrexLabs/memstate#71]
What's the status of Memstate? Almost a year since the last commit and no issues since November 2018...someone actually using Memstate?

**Comment by goblinfactory** [comment]
Hi @Bartolomeus-649  that's entirely up to you! :D

Obviously there's not a lot of movement here, we can both see that. Give memstate a try, if it adds value, then use it. It's not a massive project and it doesnt have lots of dependencies so the risks are quite low. If you find a bug, report it, and then judge the project on the response to bugs. But you can't write a project off because there are no issues :D Also you're free to fork the project, or submit pull requests.

You asked your question at a very interesting time because I'm about to start testing memstate on Azure with a custom journal writer to write to azure table storage. I plan to do that next week. @rofr and I were just chatting about #memstate a few days ago after I heard Robert being interviewed on the DotnetCoreShow on 28th June 2019 - https://dotnetcore.show/episode-28-memstate-with-robert-friberg/ 

I think this is just a case of life getting in the way. i.e. getting in my way of picking up slack when Robert is not contributing and keeping the momentum going. Also from my part while I've been presenting #memstate to some very big banks, their big wheels turn very slowly and my contracts have been quite long which meant I had little time to innovate in between. I'm currently in between banking contracts and have a few weeks dedicated to migrating some really big legacy projects over to Azure, and the plan is to use react,Azure Functions, memstate, table storage ...mmm there must be some type of MEAN acronym there? in memory RAFT? React, AzureFunction, TableStorage + memstate. (will let that percolate)

In the meantime, I suggest run your own experiments. If you like it, use it. If you're concerned about support, then test it, find a bug, report the bug and see how long it takes to get it resolved. If you're that way inclined, submit a pull request for the fix  (grin!)
Best of luck

Alan

**Comment by Simcon** [comment]
Hi @Bartolomeus-649, just to further echo what Alan said - I've used Memstate with success in a sideproject and it's been great. The best thing is you're basically just querying your data with Linq as if it's a regular in-memory C# collection because, well, it just is. No database API's. No ORMs. No lock-in. Just pure productivity. Although it's a young project it's built off another (OrigoDB) so it's feels quite stable. Check out the docs and take it for a spin!

**Comment by goblinfactory** [comment]
@Bartolomeus-649 are there issues you want to see resolved that are blocking you from being able to use memstate? If not, can we close this issue?
